# проверить что будет если убрать depends_on
# сделать вывод таблицы в stdout

version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: on-failure
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=ps123
    networks:
      - innerNet
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 30s
      retries: 3
      start_period: 5s

  filler:
    build: ./Filler/
    restart: on-failure
    container_name: filler
    entrypoint: 
      - bash
      - /home/work_dir/main.sh
    environment:
      - DB_ROOT_PASSWORD=ps123
    volumes:
      - ./Filler/work_dir:/home/work_dir:ro
    networks:
      - innerNet
    depends_on:
      mariadb:
        condition: service_healthy


networks:
  innerNet:
    name: innerNet
    driver: bridge

volumes:
  db_data:
