# проверить что будет если убрать depends_on
# сделать вывод таблицы в stdout +
# написать README

version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: on-failure
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql:Z
    env_file: ./.env
    networks:
      - innerNet
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 30s
      retries: 3
      start_period: 5s

  filler:
    build: ./Filler/
    restart: on-failure
    container_name: filler
    working_dir: /home
    entrypoint: 
      - bash
      - /home/work_dir/main.sh
    env_file: ./.env
    volumes:
      - ./Filler/work_dir:/home/work_dir:ro
    networks:
      - innerNet
    depends_on:
      mariadb:
        condition: service_healthy

  web:
    build: ./Web/
    restart: on-failure
    container_name: web
    networks:
      - innerNet
    ports:
      - "3306:8000"
    env_file: ./.env
    entrypoint:
      - npm
      - start
    depends_on:
        filler:
          condition: service_started

networks:
  innerNet:
    name: innerNet
    driver: bridge

volumes:
  db_data:
