FROM node:latest

WORKDIR /home/node/app

# RUN npm init -y

# RUN npm i -P express

# RUN npm i -P mariadb

# COPY ./main.sh /home
# COPY ./createdb.sql /home

# COPY ./data.csv /home


# ENTRYPOINT bash /home/work_dir/main.sh

# ENTRYPOINT mariadb -h tMariadb --user root -pps123