FROM bash:latest

RUN apk add mariadb-client

# RUN bash -c "echo 'This a test'"

# RUN bash -c "mkdir /myFolder"

# RUN mariadb -h 192.168.0.2 --user root -p

# COPY ./main.sh /home
# COPY ./createdb.sql /home

# COPY ./data.csv /home

WORKDIR /home

# ENTRYPOINT bash /home/work_dir/main.sh

# ENTRYPOINT mariadb -h tMariadb --user root -pps123