main:
  hosts:
    testub:
      ansible_host: 172.22.22.121
      ansible_port: 4444
      ansible_user: testu
      ansible_ssh_private_key_file: /home/tsal/Documents/keys/id_ecdsa
      ansible_password: 1234

    

prod:
  hosts:
    node1: 
      ansible_host: 192.168.56.10
      ansible_ssh_private_key_file: /media/sf_MFTI/TPOS_Home_work/HW_3/keys/node1/private_key

    node2: 
      ansible_host: 192.168.56.11
      ansible_ssh_private_key_file: /media/sf_MFTI/TPOS_Home_work/HW_3/keys/node2/private_key

    node3: 
      ansible_host: 192.168.56.12
      ansible_ssh_private_key_file: /media/sf_MFTI/TPOS_Home_work/HW_3/keys/node3/private_key      

  vars:
    ansible_user: vagrant
    ansible_password: vagrant